package com.github.sunlong.hellomonitor.common;

/**
 * User: sunlong
 * Date: 13-2-1
 * Time: 上午9:56
 */
public enum MessageCode implements IMsgCode{
    //user
    USER_GET_AUTHENTICATION_INFO_ERROR,
    USER_EXIST_ERROR,
    USER_NOT_EXIST_ERROR,
    USER_NAME_EXIST_ERROR,
    USER_NEW_PASSWORD_BLANK_ERROR,
    USER_TWICE_PASSWORD_NOT_EQUAL_ERROR,
    USER_OLD_PASSWORD_ERROR,
    USER_PASSWORD_BLANK_ERROR,
    USER_DELETE_DEFAULT_ERROR,

    USER_GROUP_EXIST_ERROR,
    USER_GROUP_NOT_EXIST_ERROR,
    USER_GROUP_PARENT_NOT_EXIST_ERROR,
    USER_GROUP_DELETE_DEFAULT_ERROR,
    USER_GROUP_UPDATE_DEFAULT_NAME_ERROR,

    ROLE_EXIST_ERROR,
    ROLE_NOT_EXIST_ERROR,
    ROLE_ID_NOT_EXIST_ERROR,
    ROLE_DELETE_DEFAULT_ERROR,
    ROLE_UPDATE_DEFAULT_ROLE_NAME_ERROR,

    RESOURCE_EXIST_ERROR,
    RESOURCE_NOT_EXIST_ERROR,
    RESOURCE_ID_NOT_EXIST_ERROR,

    ACTION_EXIST_ERROR,
    ACTION_NOT_EXIST_ERROR,

    //cloudsphere
    ZONE_NOT_EXIST_ERROR,

    POD_NOT_EXIST_ERROR,

    HOST_NOT_EXIST_ERROR,

    STORAGE_NOT_EXIST_ERROR,

    TEMPLATE_NOT_EXIST_ERROR,

    OS_TYPE_NOT_EXIST_ERROR,

    DISK_OFFERING_NOT_EXIST_ERROR,

    SERVICE_OFFERING_NOT_EXIST_ERROR,

    NETWORK_OFFERING_NOT_EXIST_ERROR,

    SECURITY_GROUP_NOT_EXIST_ERROR,

    ISO_NOT_EXIST_ERROR,
    
    CLUSTER_NOT_EXIST_ERROR,

    CLOUDSPHERE_MALFORMED_PARAMETER_ERROR,
    CLOUDSPHERE_PARAM_ERROR,
    CLOUDSPHERE_UNSUPPORTED_ACTION_ERROR,
    CLOUDSPHERE_AUTHENTICATION_ERROR,
    CLOUDSPHERE_ERROR,

    PHYSICAL_NETWORK_CREATE_ERROR,
    PHYSICAL_NETWORK_ENABLE_ERROR,
    TRAFFIC_TYPE_ADD_ERROR,

    NETWORK_SERVICE_PROVIDER_NOT_EXIST_ERROR,
    NETWORK_SERVICE_PROVIDER_ENABLE_ERROR,
    NETWORK_SERVICE_PROVIDER_ADD_ERROR,

    VIRTUAL_ROUTER_ELEMENT_NOT_EXIST_ERROR,
    VIRTUAL_ROUTER_ELEMENT_ENABLE_ERROR,
    PUBLIC_TRAFFIC_CONFIG_ERROR,

    //other
    HEX_DECODE_EXCEPTION_ERROR,
    DATA_INTEGRITY_VIOLATION_EXCEPTION_ERROR,
    VALIDATION_ERROR,

    //udcm
    UDCM_CREATE_ERROR,
    UDCM_CREATE_EXIST,
    UDCM_EDIT_ERROR,
    UDCM_DELETE_ERROR,
    UDCM_CREATE_SUCCESS,
    UDCM_EDIT_SUCCESS,
    UDCM_DELETE_SUCCESS,
    UDCM_DEVICE_BINDTEMPLATE_ERROR,
    UDCM_DEVICE_BINDTEMPLATE_SUCCESS
}